#1163 not all Flysystem adapters have the method applyPathPrefix
dustin10/VichUploaderBundle pull request #1171
Opened 2020-12-16 13:36 UTC by pieterw2w

2020-12-16 13:40 UTC, garak commented
Can you provide some context?

2020-12-17 14:22 UTC, pieterw2w commented
This fixes issue #1163

2020-12-17 14:26 UTC, garak requested changes

2020-12-17 14:26 UTC, garak commented on src/Storage/FlysystemStorage.php
> +        if (is_callable([$adapter, 'applyPathPrefix'])) {
please add native function invocation.
Ideally, you should run php-cs-fixer on your core before committing it.

2020-12-21 15:10 UTC, angelomelonas commented
@pieterw2w thanks so much for this fix!

2021-01-05 11:34 UTC, garak commented
Any news from this?

2021-01-12 10:07 UTC, pieterw2w commented
> Any news from this?

sorry, i completely forgot about this PR. I'll see if I can fix these changes.

2021-01-12 13:32 UTC, pieterw2w commented
Done!

2021-01-12 13:41 UTC, garak approved these changes

2021-01-19 11:35 UTC, merged

2021-01-19 11:37 UTC, garak commented
Released in tag `1.16.1`.
Thank you!