Php8 attributes fix
dustin10/VichUploaderBundle pull request #1215
Opened 2021-06-25 19:52 UTC by mathieupetrini

Fix PHP 8 Attribute reader

2021-06-26 14:55 UTC, garak requested changes

2021-06-26 14:55 UTC, garak commented on src/Metadata/Driver/AttributeReader.php
> +class AttributeReader implements Reader
Can we make this class final?

2021-06-26 14:55 UTC, garak commented on tests/Metadata/Driver/AttributeReaderTest.php
> +class AttributeReaderTest extends TestCase
This needs to be final

2021-06-28 08:01 UTC, garak approved these changes

2021-06-28 08:01 UTC, merged

2021-08-06 09:44 UTC, redecs commented
Thank you @mathieupetrini for adding the attributes support and @garak for reviewing. Looking forward to seeing this in a realse! 🎉

2021-09-30 13:46 UTC, adpeyre commented
Thanks @mathieupetrini !
It works for me with the dev-master version.

@garak A release soon ? :)

2021-09-30 13:57 UTC, garak commented
> Thanks @mathieupetrini ! It works for me with the dev-master version.

Don't use dev-master. Use our alias, customized with the current stable version +1 (currently, you can use 1.19-dev).
In this way, you can get the latest release now _and_ the stable release as soon as it will be out.
 
> @garak A release soon ? :)

There's no ETA at the moment.

2021-10-08 13:39 UTC, adpeyre commented
@garak The 1.19-dev version doesn't exist. ;)