Allow for Syfmony 6
dustin10/VichUploaderBundle pull request #1237
Opened 2021-11-22 14:01 UTC by tacman

Symfony 6 will be released in a few days.  This PR allows for it, and fixes a few of the deprecation errors seen with the upcoming 5.4.

I'm not sure how to handle the phpstan errors, and setting up neon.  If someone can help set that up, I can help with fixing the deprecations for 5.4.

I made some changes to the build matrix, but I think it can be improved, in particular I'm not sure when with_imagine and with_oneupbundle should be used.

2021-11-22 14:05 UTC, garak requested changes

2021-11-22 14:05 UTC, garak commented on src/Adapter/AdapterInterface.php
> +    public function recomputeChangeSet($event): void;
we can't change interface signature without a BC break.
Same applies for adding type-hints to non-final classes

2021-11-22 14:15 UTC, tacman commented
Oh.  Hmm.

So maybe I should drop this PR altogether.

Given the popularity of this bundle and the imminent release of Symfony 6,
can you or someone make the changes to support it?

Or I can continue to try.

On Mon, Nov 22, 2021 at 9:05 AM Massimiliano Arione <
***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In src/Adapter/AdapterInterface.php
> <https://github.com/dustin10/VichUploaderBundle/pull/1237#discussion_r754309072>
> :
>
> > @@ -25,5 +25,5 @@ public function getObjectFromArgs($event);
>       *
>       * @param object $event The event
>       */
> -    public function recomputeChangeSet($event);
> +    public function recomputeChangeSet($event): void;
>
> we can't change interface signature without a BC break.
> Same applies for adding type-hints to non-final classes
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/dustin10/VichUploaderBundle/pull/1237#pullrequestreview-812574995>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAEXIQNARLXHQJE35YVJFX3UNJE2LANCNFSM5IRCOQXA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2021-11-22 14:25 UTC, tacman commented
Ah, okay!  Would you like to do that?  Or can we get the Symfony 6 support
in without fixing the phpstan errors?

On Mon, Nov 22, 2021 at 9:17 AM Massimiliano Arione <
***@***.***> wrote:

> Oh. Hmm. So maybe I should drop this PR altogether. Given the popularity
> of this bundle and the imminent release of Symfony 6, can you or someone
> make the changes to support it? Or I can continue to try.
>
> I think we can simply add missing types in phpdoc
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/dustin10/VichUploaderBundle/pull/1237#issuecomment-975574214>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAEXIQKWRJW6ZLJRFQHR3ODUNJGJDANCNFSM5IRCOQXA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2021-11-22 14:34 UTC, tacman commented
Can you point me in the right direction on fixing these?


  1x: Since symfony/framework-bundle 5.3: Not setting the
"framework.session.storage_factory_id" configuration option is deprecated,
it will default to "session.storage.factory.native" and will replace the
"framework.session.storage_id" configuration option in version 6.0.
    1x in MappingDebugClassCommandTest::testNotUploadableClass from
Vich\UploaderBundle\Tests\Command

Legacy deprecation notices (2)

Other deprecation notices (24)

  8x: Since symfony/framework-bundle 5.3: The
"session.storage.factory.service" service is deprecated, use
"session.storage.factory.native", "session.storage.factory.php_bridge" or
"session.storage.factory.mock_file" instead.
    4x in UploadTest::testFileIsUploadedWithFileType from
Vich\UploaderBundle\Tests\Functional
    4x in UploadTest::testFileIsUploadedWithImageType from
Vich\UploaderBundle\Tests\Functional

  8x: Since symfony/framework-bundle 5.3: The "session.storage.mock_file"
service is deprecated, use "session.storage.factory.mock_file" instead.
    4x in UploadTest::testFileIsUploadedWithFileType from
Vich\UploaderBundle\Tests\Functional
    4x in UploadTest::testFileIsUploadedWithImageType from
Vich\UploaderBundle\Tests\Functional

  8x: Since symfony/framework-bundle 5.3: The
"session.storage.metadata_bag" service is deprecated, create your own
"session.storage.factory" instead.
    4x in UploadTest::testFileIsUploadedWithFileType from
Vich\UploaderBundle\Tests\Functional
    4x in UploadTest::testFileIsUploadedWithImageType from
Vich\UploaderBundle\Tests\Functional


On Mon, Nov 22, 2021 at 9:31 AM Massimiliano Arione <
***@***.***> wrote:

> Ah, okay! Would you like to do that? Or can we get the Symfony 6 support
> in without fixing the phpstan errors?
>
> Please, go on with your PR.
> You can ignore phpstan errors for now, I suspect the culprit is a change
> between phpstan versions (output of error messages changed and it's not
> matching anymore)
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/dustin10/VichUploaderBundle/pull/1237#issuecomment-975586699>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAEXIQNZFP23SK5ODMCIDDDUNJH3RANCNFSM5IRCOQXA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2021-11-22 15:01 UTC, tacman commented
Perfect, thanks!

What version of phpunit should we be using?  Can we safely bump to 9.5?  I
think we're running on 8.5, but locally I test with php8.  I am quite
confused about phpunit and such.

There are 19 skipped tests right now, and I'm not at all sure how to handle
those, as they're deep in the code related to FlySystem, the cache, etc.
Can I hand this off to someone with more experience?



On Mon, Nov 22, 2021 at 9:43 AM Massimiliano Arione <
***@***.***> wrote:

> All deprecations can be fixed by adjusting the configuration of the dummy
> application used for tests. You can find it in tests/Fixtures/App
> directory
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/dustin10/VichUploaderBundle/pull/1237#issuecomment-975599100>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAEXIQKOMS5OFKFJYUTSQHDUNJJIHANCNFSM5IRCOQXA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2021-11-22 15:07 UTC, garak commented
> Perfect, thanks! What version of phpunit should we be using? Can we safely bump to 9.5? I think we're running on 8.5, but locally I test with php8. I am quite confused about phpunit and such.

We're already on PHPUnit 9.5

> There are 19 skipped tests right now, and I'm not at all sure how to handle those, as they're deep in the code related to FlySystem, the cache, etc. Can I hand this off to someone with more experience?

The skipped tests depend on the environment, if you manage to get the needed dependencies in GitHub actions, they will automatically unskip

2021-12-07 15:23 UTC, jbelelieu commented
Is there any progress on merging this?

2021-12-11 15:41 UTC, garak commented
@tacman can you address the previous remarks, please?
We're waiting for this PR to release a new tag

2021-12-13 11:56 UTC, tacman commented
> The skipped tests depend on the environment, if you manage to get the needed dependencies in GitHub actions, they will automatically unskip

Can someone help me out with this?  I'm stuck on what to do, just not familiar enough with github actions to know what to do.

2021-12-13 13:22 UTC, garak commented
> > The skipped tests depend on the environment, if you manage to get the needed dependencies in GitHub actions, they will automatically unskip
> 
> Can someone help me out with this? I'm stuck on what to do, just not familiar enough with github actions to know what to do.

Just leave them as they are

2021-12-14 17:52 UTC, sxsws commented
What is the problem holding this back?

2021-12-16 16:48 UTC, garak commented
> What is the problem holding this back?

CI failures

2021-12-17 12:42 UTC, CoalaJoe commented
LTM like there are too many deprecations triggered. Should we increase the num of allow deprecations for PHP 8.1?

2021-12-21 18:55 UTC, sxsws commented
It looks like to me that @tacman has done the coding has now asked for help to get it through the tests and the one person able to help isn't?

2021-12-22 00:05 UTC, tacman commented
I wish I understood what's not working and how to fix it. I've spent hours
trying, and am stuck.  I'm happy to take advice, learn, contribute, etc.
Thanks for your comment, I'm hoping it helps move the PR forward.

On Tue, Dec 21, 2021 at 1:55 PM sxsws ***@***.***> wrote:

> It looks like to me that @tacman <https://github.com/tacman> has done the
> coding has now asked for help to get it through the tests and the one
> person able to help isn't?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/dustin10/VichUploaderBundle/pull/1237#issuecomment-999017643>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAEXIQKY7EBC7GKDKSZA2B3USDETTANCNFSM5IRCOQXA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2021-12-22 08:39 UTC, garak commented
@tacman the phpstan issues are pretty simple to solve: just look for mentioned ignored errors and remove them from the baseline file.
The deprecations in PHP 8.1 are maybe a bit trickier, but we only need to solve the direct ones.

2021-12-22 09:59 UTC, garak commented
Closing in favour of #1250 
Thanks @tacman for your effort.

2021-12-22 09:59 UTC, closed without merging

2021-12-22 12:39 UTC, sxsws commented
Why did it have to be a separate PR? the only difference I see is the 'fixed tests', which is the help this PR needed to move it forwards and merge it.

Feels like a kick in face to @tacman

2021-12-22 12:43 UTC, garak commented
Just because this PR was not ready, and the other one was.

2021-12-22 12:50 UTC, tobias-93 commented
@sxsws I never meant to insult anyone, I just felt @tacman was struggling and wanted to help.
As you can see in my PR, it took quite some iterations to get all tests up to speed and I wasn't even sure if I could get it all working anyway.
Putting my progress in this branch (and hence this PR) would have given a lot of unneccessary interference.
Only when I was kind of sure everything would work I submitted the PR.
Of course my thanks go to @tacman for his effort, I think he was quite close.

2021-12-22 17:36 UTC, tacman commented
I'll accept that, and hope to learn from it!

All good, happy solstice and such.

Tac


On Wed, Dec 22, 2021 at 7:50 AM Tobias Feijten ***@***.***>
wrote:

> @sxsws <https://github.com/sxsws> I never meant to insult anyone, I just
> felt @tacman <https://github.com/tacman> was struggling and wanted to
> help.
> As you can see in my PR, it took quite some iterations to get all tests up
> to speed and I wasn't even sure if I could get it all working anyway.
> Putting my progress in this branch (and hence this PR) would have given a
> lot of unneccessary interference.
> Only when I was kind of sure everything would work I submitted the PR.
> Of course my thanks go to @tacman <https://github.com/tacman> for his
> effort, I think he was quite close.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/dustin10/VichUploaderBundle/pull/1237#issuecomment-999553283>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAEXIQL65UWDZHIEH7KZA4LUSHCRHANCNFSM5IRCOQXA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>