fixes #1266
dustin10/VichUploaderBundle pull request #1267
Opened 2022-02-03 21:53 UTC by oleg-andreyev

fixes  #1266 

Ref. :#756 #880

2022-02-06 14:20 UTC, garak requested changes
Can you fix phpstan errors?

2022-02-11 09:51 UTC, oleg-andreyev commented
Going to take a look.

2022-02-22 13:59 UTC, oleg-andreyev commented
@garak fixed phpstan once again.

2022-03-06 15:04 UTC, garak approved these changes

2022-03-06 19:26 UTC, merged