WIP! now it's possible to define property_path
dustin10/VichUploaderBundle pull request #1283
Opened 2022-03-21 16:07 UTC by oleg-andreyev

Fixes https://github.com/dustin10/VichUploaderBundle/issues/1273

2022-03-21 16:48 UTC, garak requested changes

2022-03-21 16:48 UTC, garak commented on src/Form/Type/VichFileType.php
> +        if (!$parent = $form->getParent()) {
Can we use `$parent !== $form->getParent()`?

2022-03-21 16:48 UTC, garak commented on src/Form/Type/VichFileType.php
> +        if ($propertyPath) {
is this a boolean? If not, please use the proper comparison

2022-03-21 16:48 UTC, garak commented on src/Form/Type/VichFileType.php
> +            return $this->propertyAccessor->getValue($data, $propertyPath->getParent());
Missing blank line before `return`

2022-05-23 10:36 UTC, garak commented
@oleg-andreyev did you have time to sort this out?

2022-05-23 10:38 UTC, oleg-andreyev commented
> @oleg-andreyev did you have time to sort this out?

@garak sorry, no. But can try by end of this week

2022-05-28 14:11 UTC, VincentLanglet commented
> > @oleg-andreyev did you have time to sort this out?
> 
> @garak sorry, no. But can try by end of this week

I can try to finish this pr if you don't have time ; tell me about it @oleg-andreyev

2022-05-28 14:50 UTC, oleg-andreyev commented
Want to create functional test and will be done 👍

2022-06-25 08:16 UTC, VincentLanglet commented
Any news ? Do you need help ?

2022-06-26 17:56 UTC, oleg-andreyev commented
> Any news ? Do you need help ?

Yes, would be great. Sorry.

2022-06-28 17:02 UTC, closed without merging