Allow use of array to resolve uri
dustin10/VichUploaderBundle pull request #1365
Opened 2023-02-18 20:52 UTC by YummYume

Closes #1361.

This PR (re)allows the use of an array instead of an object to resolve a file path. I also went ahead and reintroduced this feature for the twig filter.

I moved the `fixPropertyPath` function to a utils file since it was also needed in the `directoryName` function because of the date property contained in the array.

2023-02-19 13:12 UTC, garak requested changes

2023-02-19 13:12 UTC, garak commented on src/Util/PropertyPathUtils.php
> +abstract class PropertyPathUtils
This class should be final instead, we don't want to allow extensions

2023-02-19 13:12 UTC, garak commented on src/Mapping/PropertyMapping.php
> +     * @param object $obj The object or array
The phpdoc type should be "object|array" (here and in all other points where is relevant)

2023-02-19 17:00 UTC, YummYume commented
Thanks @garak, fixed

2023-02-19 18:04 UTC, garak commented
> Thanks @garak, fixed

Actually not, please check again

2023-02-21 08:22 UTC, YummYume commented
My bad, should be good now :ok_hand:

2023-02-21 18:03 UTC, garak approved these changes

2023-02-22 17:00 UTC, merged