Add missing resolveUri method to FlysystemStorage
dustin10/VichUploaderBundle pull request #1441
Opened 2024-04-07 12:41 UTC by sovetski

It resolves a lot of problems related to Flysystem.

Without this PR, if we are using S3, Cloudflare images or other cloud storage, the public url is not the CDN one but a local url which is incorrect.

Related:

https://github.com/dustin10/VichUploaderBundle/issues/1418

2024-04-08 09:03 UTC, garak requested changes
please add a test for the new method

2024-04-10 18:22 UTC, sovetski commented
@garak should be fine now

2024-04-10 19:43 UTC, garak approved these changes

2024-04-11 06:06 UTC, merged

2024-04-12 08:37 UTC, sovetski commented
Hi @alcohol, what does your helper exactly? Can you put the code here?

2024-04-12 08:42 UTC, alcohol commented
The helper is simply an instance of `Vich\UploaderBundle\Templating\Helper\UploaderHelper`.

Instead of returning a path it is now returning a full uri.

2024-04-12 08:44 UTC, sovetski commented
@alcohol if in your helper, you change the "resolveUri" by "resolvePath" does it work?

2024-04-12 08:45 UTC, alcohol commented
<details>
<summary>Our cached S3 adapter</summary>

```php
<?php declare(strict_types=1);

namespace redacted\Flysystem;

use DateTimeInterface;
use League\Flysystem\CalculateChecksumFromStream;
use League\Flysystem\ChecksumAlgoIsNotSupported;
use League\Flysystem\ChecksumProvider;
use League\Flysystem\Config;
use League\Flysystem\DirectoryAttributes;
use League\Flysystem\FileAttributes;
use League\Flysystem\FilesystemAdapter;
use League\Flysystem\StorageAttributes;
use League\Flysystem\UnableToCopyFile;
use League\Flysystem\UnableToMoveFile;
use League\Flysystem\UnableToProvideChecksum;
use League\Flysystem\UnableToReadFile;
use League\Flysystem\UnableToRetrieveMetadata;
use League\Flysystem\UrlGeneration\PublicUrlGenerator;
use League\Flysystem\UrlGeneration\TemporaryUrlGenerator;
use Psr\Cache\CacheItemPoolInterface;
use RuntimeException;

class CacheAdapter implements FilesystemAdapter, ChecksumProvider, PublicUrlGenerator, TemporaryUrlGenerator
{
    use CacheItemsTrait;
    use CalculateChecksumFromStream;

    public function __construct(
        private readonly FilesystemAdapter $adapter,
        private readonly CacheItemPoolInterface $cache,
        private readonly string $cacheKeyPrefix = 'flysystem_',
    ) {}

    public function fileExists(string $path): bool
    {
        $item = $this->getCacheItem($path);

        if ($item->isHit()) {
            return $item->get() instanceof FileAttributes;
        }

        if ( ! $this->adapter->fileExists($path)) {
            return false;
        }

        $item->set(new FileAttributes(path: $path));

        $this->saveCacheItem($item);

        return true;
    }

    public function directoryExists(string $path): bool
    {
        $item = $this->getCacheItem($path);

        if ($item->isHit()) {
            return $item->get() instanceof DirectoryAttributes;
        }

        if ( ! $this->adapter->directoryExists($path)) {
            return false;
        }

        $item->set(new DirectoryAttributes(path: $path));

        $this->saveCacheItem($item);

        return true;
    }

    public function write(string $path, string $contents, Config $config): void
    {
        $this->adapter->write($path, $contents, $config);

        $this->addCacheEntry($path, new FileAttributes($path));
    }

    public function writeStream(string $path, $contents, Config $config): void
    {
        $this->adapter->writeStream($path, $contents, $config);

        $this->addCacheEntry($path, new FileAttributes($path));
    }

    public function read(string $path): string
    {
        try {
            $contents = $this->adapter->read($path);
        } catch (UnableToReadFile $e) {
            $this->purgeCacheItem($path);

            throw $e;
        }

        $item = $this->getCacheItem($path);

        if ( ! $item->isHit()) {
            $fileAttributes = new FileAttributes(path: $path);

            $item->set($fileAttributes);

            $this->saveCacheItem($item);
        }

        return $contents;
    }

    public function readStream(string $path)
    {
        try {
            $resource = $this->adapter->readStream($path);
        } catch (UnableToReadFile $e) {
            $this->purgeCacheItem($path);

            throw $e;
        }

        $item = $this->getCacheItem($path);

        if ( ! $item->isHit()) {
            $fileAttributes = new FileAttributes(path: $path);

            $item->set($fileAttributes);

            $this->saveCacheItem($item);
        }

        return $resource;
    }

    public function delete(string $path): void
    {
        try {
            $this->adapter->delete($path);
        } finally {
            $this->purgeCacheItem($path);
        }
    }

    public function deleteDirectory(string $path): void
    {
        try {
            foreach ($this->adapter->listContents($path, true) as $storageAttributes) {
                /** @var StorageAttributes $storageAttributes */
                $this->purgeCacheItem($storageAttributes->path());
            }

            $this->adapter->deleteDirectory($path);
        } finally {
            $this->purgeCacheItem($path);
        }
    }

    public function createDirectory(string $path, Config $config): void
    {
        $this->adapter->createDirectory($path, $config);

        $this->addCacheEntry($path, new DirectoryAttributes(path: $path));
    }

    public function setVisibility(string $path, string $visibility): void
    {
        $this->adapter->setVisibility($path, $visibility);

        $item = $this->getCacheItem($path);

        if ($item->isHit()) {
            $currentAttributes = $item->get();

            if ($currentAttributes instanceof FileAttributes) {
                $additionalAttributes = new FileAttributes(path: $path, visibility: $visibility);
            } elseif ($currentAttributes instanceof DirectoryAttributes) {
                $additionalAttributes = new DirectoryAttributes(path: $path, visibility: $visibility);
            } else {
                throw new RuntimeException('Cached item is not a file or a directory.');
            }

            $item->set($this->mergeAttributes($currentAttributes, $additionalAttributes));

            $this->saveCacheItem($item);
        }

        // We cannot create the cache item if it does not exist since we don't know if it's a file or a directory.
    }

    public function visibility(string $path): FileAttributes
    {
        try {
            return $this->getFileAttributes(
                path: $path,
                loader: fn (): FileAttributes => $this->adapter->visibility($path),
                accessor: static fn (FileAttributes $fileAttributes): ?string => $fileAttributes->visibility(),
            );
        } catch (RuntimeException $previous) {
            throw UnableToRetrieveMetadata::visibility($path, $previous->getMessage(), $previous);
        }
    }

    public function mimeType(string $path): FileAttributes
    {
        try {
            return $this->getFileAttributes(
                path: $path,
                loader: fn (): FileAttributes => $this->adapter->mimeType($path),
                accessor: static fn (FileAttributes $fileAttributes): ?string => $fileAttributes->mimeType(),
            );
        } catch (RuntimeException $previous) {
            throw UnableToRetrieveMetadata::mimeType($path, $previous->getMessage(), $previous);
        }
    }

    public function lastModified(string $path): FileAttributes
    {
        try {
            return $this->getFileAttributes(
                path: $path,
                loader: fn (): FileAttributes => $this->adapter->lastModified($path),
                accessor: static fn (FileAttributes $fileAttributes): ?int => $fileAttributes->lastModified(),
            );
        } catch (RuntimeException $previous) {
            throw UnableToRetrieveMetadata::lastModified($path, $previous->getMessage(), $previous);
        }
    }

    public function fileSize(string $path): FileAttributes
    {
        try {
            return $this->getFileAttributes(
                path: $path,
                loader: fn (): FileAttributes => $this->adapter->fileSize($path),
                accessor: static fn (FileAttributes $fileAttributes): ?int => $fileAttributes->fileSize(),
            );
        } catch (RuntimeException $previous) {
            throw UnableToRetrieveMetadata::fileSize($path, $previous->getMessage(), $previous);
        }
    }

    public function checksum(string $path, Config $config): string
    {
        $algo = $config->get('checksum_algo');
        $metadataKey = isset($algo) ? 'checksum_'.$algo : 'checksum';

        $attributeAccessor = function (StorageAttributes $storageAttributes) use ($metadataKey) {
            if (is_a($this->adapter, 'League\Flysystem\AwsS3V3\AwsS3V3Adapter')) {
                // Special optimization for AWS S3, but won't break if adapter not installed
                $etag = $storageAttributes->extraMet [...]

2024-04-12 08:48 UTC, alcohol commented
> @alcohol if in your helper, you change the "resolveUri" by "resolvePath" does it work?

It is not my helper, it is vendor code from this library. Previously we were getting `$mapping->getUriPrefix().'/'.$path;`, now we are getting the `$fs->publicUrl($path);`

2024-04-12 08:52 UTC, sovetski commented
> > @alcohol if in your helper, you change the "resolveUri" by "resolvePath" does it work?
> 
> It is not my helper, it is vendor code from this library. Previously we were getting `$mapping->getUriPrefix().'/'.$path;`, now we are getting the `$fs->publicUrl($path);`

As I am not able to do it at the moment, you can try to edit the vendor's code just to see what happens and put the original code back? I am not using S3 or this helper, that is why I need more details from your side if possible, to be able to find a fix

2024-04-12 08:53 UTC, alcohol commented
The behaviour documented here has changed if you use the `FlysystemStorage` implementation: https://github.com/dustin10/VichUploaderBundle/blob/master/docs/generating_urls.md#generating-a-url-in-a-controller

I am not saying this change is bad, but it drastically differs from what is documented and was previously default behaviour (previously for the `FlysystemStorage` storage it was simply falling back to the `resolveUri` method from the `AbstractStorage` implementation).

2024-04-14 13:24 UTC, Cryde commented
Hello 

I had the same issue, I guess bundle like https://github.com/1up-lab/OneupFlysystemBundle/tree/main are not "ready" for this change because I can't see where we can configure public urls (https://flysystem.thephpleague.com/docs/usage/public-urls/) 
Or maybe I miss something ?

2024-04-14 13:43 UTC, garak commented
Never used flysystem myself, please let me know if I need to revert this change

2024-04-14 14:06 UTC, sovetski commented
@Cryde I don't know if it can help, but for Flysystem, I am using this package and it works as expected: [thephpleague/flysystem-bundle](https://github.com/thephpleague/flysystem-bundle) as it is recommended by VichUploaderBundle here: https://github.com/dustin10/VichUploaderBundle/blob/master/docs/storage/flysystem.md#integrating-with-thephpleagueflysystem-bundle

@garak as mentionned @alcohol, maybe you can put it in a major release instead?

2024-04-14 14:09 UTC, garak commented
I could put it in a major, but a major release is not currently planned

2024-04-19 08:47 UTC, andyexeter commented
This update broke things for us too. We are storing images in S3 using a Cloudfront URL as a `uri_prefix`. The `uri_prefix` config is now completely ignored and the S3 URL is returned. Please revert this.

2024-04-19 09:04 UTC, sovetski commented
> This update broke things for us too. We are storing images in S3 using a Cloudfront URL as a `uri_prefix`. The `uri_prefix` config is now completely ignored and the S3 URL is returned when using the `\Vich\UploaderBundle\Templating\Helper\UploaderHelper::asset` method.

It solves a problem that shouldn't be there in the first place. I'm not opposed to reverting this change, but do you have a better approach to suggest?

Reverting is just a way to put the problem back; I find suggesting an improvement more interesting than wiping everything out at once.

If everyone agrees to test, I can submit a new pull request to fix the issue for existing projects. But again, just because it works with a makeshift solution doesn't mean it should never evolve (in my opinion)

2024-04-19 09:09 UTC, garak commented
What about adding an alternate storage? We need to avoid breaking existing implementations

2024-04-19 09:21 UTC, andyexeter commented
I understand that it solves a problem, but it does so by breaking existing functionality.

Forgive me if I'm misunderstanding, but looking at this code:

https://github.com/dustin10/VichUploaderBundle/blob/fec8c14c0c4ddd7f2bcd4b58fadb1222a7d2b195/src/Storage/FlysystemStorage.php#L121-L125

The code within the `try` block completely ignores the `uri_prefix` config, doesn't it? So it breaks for anyone using any `uri_prefix`?

2024-04-19 09:31 UTC, sovetski commented
@garak the PR is ready to rollback changes: https://github.com/dustin10/VichUploaderBundle/pull/1444