Revert changes of #1441
dustin10/VichUploaderBundle pull request #1444
Opened 2024-04-19 09:31 UTC by sovetski

It looks like it is a breaking change, as mentionned by 3 people here: https://github.com/dustin10/VichUploaderBundle/pull/1441

Maybe in the future it will be implemented in a major release (I hope)

2024-04-19 09:33 UTC, garak requested changes
What about updating the documentation to suggest this possible solution? So other devs can add this class (the old one I mean) and exploit this implementation.

2024-04-19 09:41 UTC, sovetski commented
@garak it's a good idea. I can add this information to the documentation for people who will want this feature. With custom storage, it will be simple to implement. Let me try to explain it.

2024-04-20 06:31 UTC, garak requested changes
Sorry, yesterday I was in a hurry and didn't notice the invalid markdown. Could you fix it please?

2024-04-20 08:43 UTC, sovetski commented
@garak was it related to the last link that I added? If yes, I fixed it, and used a markdown validator to be sure that it is valid.

2024-04-20 14:35 UTC, garak commented
> @garak was it related to the last link that I added? If yes, I fixed it, and used a markdown validator to be sure that it is valid.

As you can see in the related Action, we enforce a custom rule about the maximum length of the lines.

2024-04-22 18:13 UTC, sovetski commented
> FlysystemStorage is final, you cannot extend it.

Yes, maybe my wording is not correct, but I was meaning that we have to duplicate its code

2024-04-23 06:58 UTC, garak commented
@sovetski still waiting for a fix in the markdown

2024-04-23 07:26 UTC, sovetski commented
@garak sorry for the delay, it looks OK now

2024-04-23 07:39 UTC, merged