CWE-434: Unrestricted Upload of File with Dangerous Type. Polyglot fi…
dustin10/VichUploaderBundle pull request #1469
Opened 2024-09-30 16:36 UTC by jphetphoumy

Some unit tests were broken after my changes. I tried to update the tests based on the following Symfony Component

https://github.com/symfony/symfony/blob/10ac2449d459117ca7318c3773e613b90b9a08e3/src/Symfony/Component/HttpFoundation/File/File.php#L53-L59

https://github.com/symfony/symfony/blob/10ac2449d459117ca7318c3773e613b90b9a08e3/src/Symfony/Component/Mime/MimeTypes.php#L142

Issue: #1468

2024-09-30 17:00 UTC, garak commented on src/Naming/OrignameNamer.php
> +        if ($extension = $this->getExtension($file)) {
Please avoid implicit casting

2024-10-01 13:14 UTC, garak requested changes

2024-10-01 13:33 UTC, jphetphoumy commented on src/Naming/SlugNamer.php
> +        $slug = $extension ? \sprintf('%s.%s', $basename, $extension) : $basename;
There is implicit casting in Base64Namer from the master branch, do you want me to change it here too ? 

https://github.com/dustin10/VichUploaderBundle/blob/8056cd5561507ccf599500449cb95970ffb41ca7/src/Naming/Base64Namer.php#L44-L46

2024-10-01 17:47 UTC, garak commented on src/Naming/SlugNamer.php
> +        $slug = $extension ? \sprintf('%s.%s', $basename, $extension) : $basename;
avoiding adding new ones is enough

2024-10-12 12:14 UTC, garak commented on tests/Naming/SlugNamerTest.php
>              // case -> original name, result pattern
this comment needs to be adapted, since now there are three values

2024-10-12 12:14 UTC, garak commented on tests/Naming/SmartUniqidNamerTest.php
>              // case -> original name, result pattern
same here: add the new parameter

2024-10-12 17:01 UTC, garak approved these changes

2024-10-12 17:01 UTC, merged